version: "3.5"

services:
    web:
        build: .
        depends_on:
            - db
        ports:
        - 5000:5000
        networks:
            - default
        volumes:
            - ./:/webapp/
            - ./migrations:/webapp/migrations
        restart: always
    db:
        environment:
            # postgres://:@/flask-rest-api-db
            POSTGRES_USER: flask-rest-api-db-user
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: flask-rest-api-db
        image: postgres:latest
        networks:
            - default
        ports:
            - 5405:5432
        restart: always
        volumes:
            - ./postgres-data:/var/lib/postgresql/data